### ISSUE TITLE
Pointcloud_Output not visible

### ISSUE THREAD

**Issue by Pran-Seven** [tomlogan501/pointcloud_merger#4]
Hey! I came across his neat code after much struggle to find pointcloud stitch/merger code. I was able to add the nodelet to my repository and launch it, but I can't seem to get the output on rviz. I can see terminal messages that it is able to subscribe to the pointclouds given and I can also see the individual pointclouds on rviz but can't seem to get an output from the pointcloud_merger_nodelet. I am using code from the master branch and running with ros melodic and two intel realsense d400 series depth cameras.

**Comment by uzbayk** [comment]
I have the same issue, I'm using two 32 Channel LiDAR's from a rosbag and it seems it doesn't merge anything.

**Comment by tomlogan501** [comment]
Is it working with the test bags ?

**Comment by uzbayk** [comment]
As I can see there isn't any bags in the repo, or maybe I couldn't find them. I have tried the package with test world and sample_node_test too and it seems to be working. But not with my real data.

**Comment by Pran-Seven** [comment]
In my case at least, the issue seemed to arise with the time synchrnoization, so I just removed that and used a thread in the constructor itself to call the merge function. Test [pcd's](https://github.com/tomlogan501/pointcloud_merger/tree/main/test/data) are available here.
